before_commands:
    - "composer install --prefer-source"

filter:
    paths: ["src/*"]
    excluded_paths:
        - "tests/"
        - "build/"
    dependency_paths:
        - vendor/

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            tests:
                override:
                    - command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                      coverage:
                          file: 'clover.xml'
                          format: clover

tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["build/*", "tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["build", "tests", "vendor"]
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml
            design_rules: { eval_expression: false }
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "tests/*"]
    php_hhvm:
        enabled: true
        filter:
            paths: ["src/*", "tests/*"]
